// <auto-generated />
using System;
using Dwight;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dwight.Migrations
{
    [DbContext(typeof(DwightDbContext))]
    [Migration("20221007162838_cwl-incrementing-reminders")]
    partial class cwlincrementingreminders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dwight.ClashMember", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MainTag")
                        .HasColumnType("integer");

                    b.Property<bool>("Remind")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("GuildId", "DiscordId");

                    b.HasIndex("DiscordId");

                    b.ToTable("clan_members", (string)null);
                });

            modelBuilder.Entity("Dwight.CurrentWarReminder", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CwlReminderLastPosted")
                        .HasColumnType("integer");

                    b.Property<int>("CwlRemindersPosted")
                        .HasColumnType("integer");

                    b.Property<bool>("DeclaredPosted")
                        .HasColumnType("boolean");

                    b.Property<string>("EnemyClan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReminderPosted")
                        .HasColumnType("boolean");

                    b.Property<bool>("StartedPosted")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("current_wars", (string)null);
                });

            modelBuilder.Entity("Dwight.GuildSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ClanTag")
                        .HasColumnType("text");

                    b.Property<decimal>("CoLeaderRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ElderRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GeneralChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UnverifiedRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("VerifiedRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WarChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WarRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WelcomeChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("guild_settings", (string)null);
                });

            modelBuilder.Entity("Dwight.ClashMember", b =>
                {
                    b.HasOne("Dwight.GuildSettings", null)
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwight.CurrentWarReminder", b =>
                {
                    b.HasOne("Dwight.GuildSettings", null)
                        .WithOne("CurrentWarReminder")
                        .HasForeignKey("Dwight.CurrentWarReminder", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwight.GuildSettings", b =>
                {
                    b.Navigation("CurrentWarReminder");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
